### ISSUE TITLE
Things to be added to documentation

### ISSUE THREAD

**Issue by muroc** [quedexnet/python-api#4]
This issue contains a TODO list for API documentation changes. If you think something should be added here, please leave a comment.

- [x] Order of events after successful connection
- [x] Explain that API is in plain notation (both futures and options), i.e. prices are expressed in BTC per USD
- [x] Explain different session states in documentation of sending orders
- [x] Mention twisted threading
- [x] Short instruction on how to get PGP keys and account id

**Comment by wgromniak** [comment]
- [ ] Explain that API is in plain notation (both futures and options), i.e. prices are expressed in BTC per USD.

**Comment by muroc** [comment]
Added.

**Comment by wgromniak** [comment]
Mention that we have different session states.

**Comment by muroc** [comment]
Added.

**Comment by wgromniak** [comment]
Short instruction, how to get PGP keys, account id (TODOs in Simple Trading tutorial).

**Comment by muroc** [comment]
Added

**Comment by wgromniak** [comment]
Test compatibility with Python 3 and mention compatibility in the docs.

**Comment by wgromniak** [comment]
@muroc, seems to me that everything from the first post is covered. Let's close this one and create a separate task for Python 3 compat?

**Comment by muroc** [comment]
ack
